version: "3.1"
services:
  mysql:
    image: mysql:8.0.41
    container_name: ${MYSQL_REMOTE_HOST:-mysqlHost}
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
      MYSQL_DATABASE: ${MYSQL_DB:-cscart}
    volumes:
      - ./app/db:/var/lib/mysql
    ports:
      - "${MYSQL_REMOTE_PORT:-3306}:3306"

  nginx:
    image: nginx:alpine
    container_name: ${NGINX_CONTAINER_NAME:-cscartNginx}
    working_dir: /etc/nginx
    volumes:
      - ./app:/app
      - ./app/sphinx/sphinx-3.3.1:/root/sphinx-3.3.1
      - ./config/nginx:/etc/nginx/conf.d
    ports:
      - "${HTTP_REMOTE_PORT:-8080}:80"
      - "${HTTPS_REMOTE_PORT:-443}:443"
      - "9306:9306"
    depends_on:
      # - php7.3
      - php7.4
      # - php8.0

  php7.3:
    build:
      context: ./config/php7.3
      dockerfile: Dockerfile
    container_name: ${CONTAINER_PREFIX}php7.3
    working_dir: /app
    volumes:
      - ./app:/app
      - ./config/php7.3/php-ini-overrides.ini:/usr/local/etc/php/conf.d/00-php.ini
      - ./bin/sendmail:/usr/local/bin/sendmail
    environment:
        PHP_IDE_CONFIG: serverName=localhost

  php7.4:
    build:
      context: ./config/php7.4
      dockerfile: Dockerfile
    container_name: ${CONTAINER_PREFIX}php7.4
    working_dir: /app
    volumes:
      - ./app:/app
      - ./app/sphinx/sphinx-3.3.1:/root/sphinx-3.3.1
      - ./config/php7.4/php-ini-overrides.ini:/usr/local/etc/php/conf.d/00-php.ini
      - ./bin/sendmail:/usr/local/bin/sendmail
    environment:
        PHP_IDE_CONFIG: serverName=localhost

  php8.0:
    build:
      context: ./config/php8.0
      dockerfile: Dockerfile
    container_name: ${CONTAINER_PREFIX}php8.0
    working_dir: /app
    volumes:
      - ./app:/app
      - ./config/php8.0/php-ini-overrides.ini:/usr/local/etc/php/conf.d/00-php.ini
      - ./bin/sendmail:/usr/local/bin/sendmail
    environment:
        PHP_IDE_CONFIG: serverName=localhost
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ${CONTAINER_PREFIX}pma
    environment:
      PMA_HOST: ${MYSQL_REMOTE_HOST:-mysqlHost}
      PMA_USER: root
      PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
    restart: always
    ports:
      - ${PHPMYADMIN_PORT:-8081}:80
  sphinx:
    image: jc21/sphinxsearch
    container_name: ${CONTAINER_PREFIX}sphinx
    ports:
      - ${SPHINX_SphinxQL:-9306}:9306
      - ${SPHINX_SphinxAPI:-9312}:9312
    volumes:
      - "./config/sphinx:/etc/sphinx"
      - "./app/sphinx:/var/lib/sphinx"
# Change default subnet addresses (for uncomment - delete only '#'):
#networks:
#  default:
#    driver: bridge
#    ipam:
#      driver: default
#      config:
#      - subnet: 10.10.0.1/16

