#!/bin/bash

DOMAIN_LIST=""
CONTAINER_PREFIX=""
PHPMYADMIN="N"

while [ -n "$1" ]
do
case "$1" in
--domain_list) DOMAIN_LIST="$2"
shift ;;
--container_prefix) CONTAINER_PREFIX="$2"
shift ;;
--phpmyadmin) PHPMYADMIN="$2"
shift ;;
esac
shift
done

if [[ ! ${CONTAINER_PREFIX} || ! ${DOMAIN_LIST} ]]
then
	echo 'The CONTAINER_PREFIX, DOMAIN_LIST params are required';
	exit;
fi

MYSQL_HOST="${CONTAINER_PREFIX}-mysql"
NGINX_HOST="${CONTAINER_PREFIX}-nginx"

declare -A aliasArr
aliasArr[$NGINX_HOST]=$DOMAIN_LIST
aliasArr[$MYSQL_HOST]=$MYSQL_HOST
if [[ ${PHPMYADMIN} == "Y" ]]; then
	aliasArr["${CONTAINER_PREFIX}-pma"]="${CONTAINER_PREFIX}-pma.local"
fi
aliasArr["${CONTAINER_PREFIX}-sphinx"]="${CONTAINER_PREFIX}-sphinx.local"

# iterate over each machine
docker ps -a --format "{{.Names}}" \
| while read -r MACHINE; do

	MACHINE_IP="$(docker inspect --format='{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' ${MACHINE} 2>/dev/null)"

	if [[ ${aliasArr[$MACHINE]} ]]
	then
		DOMAIN_NAME=$(echo ${aliasArr[$MACHINE]} | tr "," "\n")

    for addr in $DOMAIN_NAME
    do
			echo "add ${MACHINE_IP}	${addr}"
			[[ -n $MACHINE_IP ]] && sudo /bin/bash -c "echo \"${MACHINE_IP}	${addr}\" >> /etc/hosts"
			export no_proxy=$no_proxy,$MACHINE_IP
    done
	fi

done
