#!/bin/bash

NGINX_CONTAINER_NAME=""
MYSQL_REMOTE_HOST=""
DOMAIN_LIST=""

while [ -n "$1" ]
do
case "$1" in
--domain_list) DOMAIN_LIST="$2"
shift ;;
--mysql_remote_host) MYSQL_REMOTE_HOST="$2"
shift ;;
--nginx_container_name) NGINX_CONTAINER_NAME="$2"
shift ;;
esac
shift
done

if [[ ! ${NGINX_CONTAINER_NAME} ||  ! ${MYSQL_REMOTE_HOST}  ||  ! ${DOMAIN_LIST} ]]
then
	echo 'The NGINX_CONTAINER_NAME, MYSQL_REMOTE_HOST, DOMAIN_LIST params are required';
	exit;
fi

declare -A aliasArr
aliasArr[$NGINX_CONTAINER_NAME]=$DOMAIN_LIST
aliasArr[$MYSQL_REMOTE_HOST]=$MYSQL_REMOTE_HOST

# iterate over each machine
docker ps -a --format "{{.Names}}" \
| while read -r MACHINE; do

	MACHINE_IP="$(docker inspect --format='{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' ${MACHINE} 2>/dev/null)"

	if [[ ${aliasArr[$MACHINE]} ]]
	then
		DOMAIN_NAME=$(echo ${aliasArr[$MACHINE]} | tr "," "\n")

    for addr in $DOMAIN_NAME
    do
			echo "add ${MACHINE_IP}	${addr}"
			[[ -n $MACHINE_IP ]] && sudo /bin/bash -c "echo \"${MACHINE_IP}	${addr}\" >> /etc/hosts"
			export no_proxy=$no_proxy,$MACHINE_IP
    done
	fi

done
