#!/bin/bash

# default
DOMAIN_LIST=""
CONTAINER_PREFIX=""

while [ -n "$1" ]
do
case "$1" in
--domain_list) DOMAIN_LIST="$2"
shift ;;
--container_prefix) CONTAINER_PREFIX="$2"
shift ;;
esac
shift
done

echo "Purge domains from /etc/hosts"

if [[ ${CONTAINER_PREFIX} ]]
then
    DOMAIN_LIST="${DOMAIN_LIST},${CONTAINER_PREFIX}-mysql"
    DOMAIN_LIST="${DOMAIN_LIST},${CONTAINER_PREFIX}-pma.local"
    DOMAIN_LIST="${DOMAIN_LIST},${CONTAINER_PREFIX}-sphinx.local"
else
    DOMAIN_LIST="${DOMAIN_LIST},pma.local"
fi

if [[ ${DOMAIN_LIST} ]]
then
  DOMAIN_NAME=$(echo ${DOMAIN_LIST} | tr "," "\n")

  for addr in $DOMAIN_NAME
  do
    sudo sed -i "/${addr}$/d" /etc/hosts
  done
fi
