#!/bin/bash

MYSQL_USER="root"
MYSQL_PASSWORD="root"
MYSQL_REMOTE_HOST="localhost"
MYSQL_DB="cscart"
DOMAIN_LIST="localhost"
CONTAINER_PREFIX=""

while [ -n "$1" ]
do
case "$1" in
--db_user) MYSQL_USER="$2"
shift ;;
--db_pass) MYSQL_PASSWORD="$2"
shift ;;
--remote_host) MYSQL_REMOTE_HOST="$2"
shift ;;
--db_name) MYSQL_DB="$2"
shift ;;
--container_prefix) CONTAINER_PREFIX="$2"
shift ;;
--domain_list) DOMAIN_LIST="$2"
shift ;;
--not_cscart) NOT_CSCART="$2"
shift ;;
*) echo "$1 is not an option";;
esac
shift
done

NGINX_HOST="${CONTAINER_PREFIX}-nginx"

# create work folder
if [ ! -f $(pwd)/app/www ]
then
  mkdir -p $(pwd)/app/www;
fi

# copy and replace nginx/app.conf
if [ ! -f $(pwd)/config/nginx/app.conf ]
then
  echo "Create nginx config"
  mkdir -p $(pwd)/config/nginx;
  cp $(pwd)/config/files/app.conf.example $(pwd)/config/nginx/app.conf
fi

if [[ ! ${NOT_CSCART} ||  ${NOT_CSCART} == "N" ]]
then
  # generate local_conf.php
  if [ ! -f $(pwd)/config/files/local_conf.php ]
  then
    echo "Generate local_conf.php"
    cp $(pwd)/config/files/local_conf.php.example $(pwd)/config/files/local_conf.php

    DOMAIN_NAME=$(echo "$DOMAIN_LIST"|cut -d ',' -f1)

    sed -i "s/%MYSQL_USER%/$MYSQL_USER/g;s/%MYSQL_PASSWORD%/$MYSQL_PASSWORD/g;s/%MYSQL_REMOTE_HOST%/$MYSQL_REMOTE_HOST/g;s/%MYSQL_DB%/$MYSQL_DB/g;s/%DOMAIN_NAME%/$DOMAIN_NAME/g;" $(pwd)/config/files/local_conf.php
  fi
else
  # copy defaul index.php
  if [ ! -f $(pwd)/app/www/index.php ]
  then
    echo "Copy default index.php"
    cp $(pwd)/config/files/index.php.example $(pwd)/app/www/index.php
  fi
fi

# add ssl cert
if [ ! -f $(pwd)/app/ssl/ssl.crt ]
then
  $(dirname "$0")/reinit_ssl --domain_list $DOMAIN_LIST --container_prefix $CONTAINER_PREFIX
fi
