#!/bin/bash

MyUSER="root"
MyPASS="root"
MyHOST="localhost"
MyDB="cscart"

FILE=""
CHECK=""

MYSQL="$(which mysql)"

while [ -n "$1" ]
do
case "$1" in
--root_pass) MyPASS="$2"
shift ;;
--remote_host) MyHOST="$2"
shift ;;
--db_name) MyDB="$2"
shift ;;
--file_name) FILE="$2"
shift ;;
--not_cscart) NOT_CSCART="$2"
shift ;;
--additional_check) CHECK="$2"
shift ;;
*) echo "$1 is not an option";;
esac
shift
done

# check exist DB
if [[ $CHECK ]];
then
  exist="$($MYSQL -u $MyUSER -h $MyHOST -p$MyPASS -Bse 'SHOW DATABASES' | grep $MyDB)"

  if [[ -z $exist ]];
  then
    $($MYSQL -u $MyUSER -h $MyHOST -p$MyPASS -Bse "CREATE DATABASE $MyDB")

    echo "DB created"
  else
    echo "DB exists"
  fi
fi
# /check exist DB

if [[ ${FILE} ]];
then
  echo "Restore file: $(pwd)/bck/$FILE"

  if [ -f $(pwd)/bck/$FILE ]
  then
    case $FILE in
      *".gz")
        gunzip < $(pwd)/bck/$FILE | $MYSQL -u $MyUSER -h $MyHOST -p$MyPASS $MyDB
        ;;
      *".zip")
        unzip -p $(pwd)/bck/$FILE | $MYSQL -u $MyUSER -h $MyHOST -p$MyPASS $MyDB
        ;;
      *)
        # $MYSQL -u $MyUSER -h $MyHOST -p$MyPASS $MyDB < $(pwd)/bck/$FILE

        # PV is utility to display progress
        pv $(pwd)/bck/$FILE | $MYSQL -u $MyUSER -h $MyHOST -p$MyPASS $MyDB
        ;;
    esac

    echo "The file restored"

  else
    echo "The file doesn't exists"
  fi
else
  echo "File path empty"
fi

if [[ ! ${NOT_CSCART} ||  ${NOT_CSCART} == "N" ]]
then
  # check cscart_logs
  if [[ $CHECK ]];
  then
    $(dirname "$0")/generate_logs_table --root_pass $MyPASS --remote_host $MyHOST --db_name $MyDB
  fi
  # /check cscart_logs
fi